### ISSUE TITLE
[itch] Redeem itch.io

### ISSUE THREAD

**Issue by DealsBeam** [HCLonely/user.js#11]
Hello,

can you please add ItchClaim https://github.com/Smart123s/ItchClaim and Freetchio https://github.com/ShaigroRB/freetchio to the list of sites to detect to redeem itch.io games?

Thank you.

**Comment by HCLonely** [comment]
ItchClaim was added. But Freetchio is not supported.

**Comment by DealsBeam** [comment]
Thank you
