### ISSUE TITLE
AuTo Redeem Steamkey 复制检测问题

### ISSUE THREAD

**Issue by Mishasama** [HCLonely/user.js#14]
这个复制激活的功能会阻断复制的动作，导致要复制的KEY无法进入剪贴板中。
这个有点烦人，能不能在触发激活的同时复制到剪贴板中？很多像是KEY但又不是要STEAM激活的东西就没法正常复制了。

**Comment by HCLonely** [comment]
经测试，复制激活功能并不会阻止默认复制事件

**Comment by Mishasama** [comment]
> 经测试

理解不了，我 EDGE/CHROME/FIREFOX 都测试过是一样的问题。
会不会是你弹窗跳出得太快，导致选择高亮的焦点丢失得太快而导致剪贴板来不及捕获内容？（我硬件性能相对很差）

能不能在脚本里直接加一个将复制的内容直接再发送一遍到剪贴板？这样就不管什么环境都不会有问题了。

注意是`复制的内容`，而不是`检测到的KEY`。
比如 `ABC123-12345-ABCDEFG` 这样的东西。

**Comment by HCLonely** [comment]
新增了在弹窗之前向剪切板发送内容
