### ISSUE TITLE
AuTo Redeem Steamkey

### ISSUE THREAD

**Issue by whyjxz14** [HCLonely/user.js#6]
licenses
https://store.steampowered.com/account/licenses/
页面是不是ui乱了。
我这里重复了

**Comment by HCLonely** [comment]
我这是正常的

**Comment by whyjxz14** [comment]
又看了一下

**Comment by HCLonely** [comment]
你关了其他脚本试试，是不是有冲突的

**Comment by whyjxz14** [comment]
又看了一下是steam redeem sub会造成问题，而且好像提供的内容和AuTo Redeem Steamkey有重复？

**Comment by HCLonely** [comment]
steam redeem sub是从这里拆除来的，装了AuTo Redeem Steamkey就不用steam redeem sub了
