### ISSUE TITLE
[itch] 希望新增可入庫的網站

### ISSUE THREAD

**Issue by bestpika** [HCLonely/user.js#7]
希望可以在下面這個網站使用入庫功能
<https://freegames.codes/>
範例網址
<https://freegames.codes/game/2635/time-travelling-navy-seal-ninja-warrior/>
右邊有個「Get It Free」的按鈕是連到 itch 的，希望可以直接在頁面入庫。
謝謝

**Comment by HCLonely** [comment]
已支持
